# Base configs
baseurl: "https://foxxmd.github.io/photography-portfolio"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Matt Fox"
subtitle: ""
author: "Matt Foxx"
header:
 title: "Photography"
 subtitle: "by Matt Foxx"
footer:
 name: "Hi! I'm Matt Foxx (FoxxMD)"
 bio: "I'm a full-stack developer, outdoor adventurist, and sometimes a photographer. These are just a few of my favorite captured moments."
 github: "Find my a href=\"https://matthewfoxx.com\">developer portfolio here.</a> This photography showcase was created by <a href=\"https://github.com/ramswaroop/photography\">Ram Patra</a>, check out there amazing work as well!"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  #twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/matthew.foxx"
  #dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/matthew-duncan-8b661321/"
  github: "https://www.github.com/FoxxMD"
